services:

  # ubuntu server
  ubuntu_test:
    build: .
    container_name: ubuntu_container
    restart: always
    command: ["sleep","infinity"]
    volumes:
      - './Docker/Data/Ubuntu_Test:/exchange:rw'
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - "5555:22"
    network_mode: bridge